### ISSUE TITLE
Unable to use Custom font-family

### ISSUE THREAD

**Issue by Mahesha-Bhat** [socrypto/react-native-highcharts-wrapper#1]
hi,
Is there any way i can provide custom font-family to highcharts which is used in entire application.
I am using expo andI haven't detached it 
please help me to resolve this issue.

**Comment by socrypto** [comment]
Hi @Mahesha-Bhat

The font-family can be set in `options.chart.style.fontFamily` object which is passed into the `ChartView`.

Closing but please let me know if it's not appearing for you and will reopen.
