### ISSUE TITLE
RNCWebView was not found in the UIManager

### ISSUE THREAD

**Issue by marc-tech** [socrypto/react-native-highcharts-wrapper#4]
Hello, I get this error with your package, it seems to be corrected by changing the "react-native-webview" dependencies from version "8.1.1" to => "6.11.1"

because webview has been removed from this update : https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1#819

other related issue : 
https://github.com/TradingPal/react-native-highcharts/issues/112
https://github.com/react-native-community/react-native-webview/issues/851
https://github.com/react-native-community/react-native-webview/issues/534

**Comment by socrypto** [comment]
Hi @marc-tech which platform are you getting this issue on? iOS I assume?

**Comment by marc-tech** [comment]
no Android, but we have the same problem with ios even with the v6.11.1

**Comment by quanghungit** [comment]
> no Android, but we have the same problem with ios even with the v6.11.1

hi @marc-tech . have you fixed it?
